# Preface {.unnumbered}

*Version 1.0, October 2025*

This e-learning course is intended for students to work through it at their own pace. There are no sessions held in presence. However, students can reach out to the lecturer for questions and support at any time via email. The course is structured along six chapters that build on each other. Many sections are interactive and contain links and videos to consult. For more information on the course please see the information document of the course.

The course is divided into three blocks. In the introductory block, students are introduced to basic concepts and the theoretical assumptions of economics (Chapters 1-2). This is followed by a block on the problem analysis addressing the ecological and social challenges faced by the current economic and societal system (Chapter 3). In the final block, participants explore strategies, the role of the state, and economic policy paradigms, and bring these together in a synthesis that provides starting points for shaping a sustainable economy (Chapters 4-6).

Below you will find the contents of the course. Following the script will guide you through all the chapters and learning material in a sensible order. Since this course requires a high degree of autonomy in acquiring the material, we also encourage you to contact us via email if you want to discuss questions (see information document).

::::: learning
::: learning-header
**Learning Outcomes**
:::

::: learning-body
Students can:

-   understand that there are different theories in economics and are able to name them.
-   can identify the foundations of the emerging field of sustainable economics.
-   can distinguish between the problem analyses and solution approaches of sustainable economics and those of today’s dominant school of thought (neoclassical and environmental economics).
-   are able to critically question both traditional and new economic approaches (concepts) and assess the conflicts inherent in them.
-   can reflect on the strengths and weaknesses of different theoretical approaches, both in general and in relation to concrete problems.
-   can analyse how alternative economic models (e.g., circular economy, post-growth economics) function and evaluate their potential and limitations for economic policy.
-   acquire basic knowledge about measures and transformation scenarios for implementing alternative economic models beyond the focus on maximizing profits and goods production.
:::
:::::

**Assessment**

The Assessment is based on two parts.

The first part is a written exam. The exam covers all topics discussed in the script up to (and including) Chapter 3 (problem analysis). The exam can be conducted anytime you feel ready to take it. If you feel ready to take the exam, contact us ([nicola.bezzola@unibe.ch](mailto:nicola.bezzola@unibe.ch)) to arrange a time to take the exam. It is held in person. Once you contact us, we organise a room for you to take the exam. The exam is in a written format on ilias and will take 30 minutes. You need 60% of the points to pass the exam. If you fail the first attempt, you can take a second attempt.

The second part of this assessment requires you to write a reflective essay on the material you have studied and your understanding of economics and the economy. We invite you to consider how the course material has (or hasn't) changed your understanding of economics and the economy in the context of sustainable transformation. Use the questions below to guide your reflection paper. However, you can also refer to other sources if you find them relevant for your reflection. You may use any resources. Students must sign a declaration of authorship. The written paper should comprise 6,000–7,500 characters (excluding spaces, the reference list, the title page, footnotes, headers and footers, lists, tables, figures and appendices). This corresponds to approximately three pages.

Guiding questions

-   How has your understanding of economics changed as a result of taking this course? What implications does this have for your understanding of sustainable transformation?

-   How has your understanding of the economy changed as a result of this course? What are the implications for your understanding of sustainable transformation?

-   What role does an understanding of economics play in the context of a sustainable transformation?

[Please submit your reflection paper via ilias.](https://ilias.unibe.ch/go/exc/3517790)

Both parts of the assessment can be done and submitted at any time. The course counts as completed as soon as students have worked through all chapters and passed both parts of the assessment. The course is graded with pass or fail.

Please note that the exam and the reflection paper must be completed **by 30 May 2027 at the latest**.

**Reading guide**

::: {.callout-note collapse="true"}
### Definitions and further readings
:::

::: {.callout-tip collapse="true"}
### Examples and reflections
:::

::: {.callout-caution collapse="true"}
### Exercises and links to ILIAS
:::
